# Generated by Django 5.2.1 on 2025-05-26 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useragentresponsedata',
            old_name='request_data',
            new_name='response_data',
        ),
        migrations.AddField(
            model_name='useragent',
            name='request_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useragent',
            name='user_agent_id',
            field=models.CharField(default='<function uuid4 at 0x7fa9d1e97100>', max_length=200, unique=True),
        ),
        migrations.DeleteModel(
            name='UserAgentRequestData',
        ),
    ]
