# Generated by Django 5.2.1 on 2025-05-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_rename_request_data_useragentresponsedata_response_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useragent',
            name='user_agent_id',
            field=models.CharField(default='8a14287e-0143-43e8-b470-101d013df101', max_length=200, unique=True),
        ),
    ]
